export const products = [
  // Row 1
  {
    category: "Avatars",
    subcategory: "Human-like",
    productName: "Human-like Avatar 1",
    creatorName: "Creator name",
    rating: 5.0,
    price: 10.5,
    slug: "human-like-avatar-1",
    platforms: ["vr-chat-quest", "vr-chat-pcvr"],
  },
  {
    category: "Avatars",
    subcategory: "Anthro & Furry",
    productName: "Anthro Furry Avatar 1",
    creatorName: "Creator name",
    rating: 5.0,
    price: 25.99,
    slug: "anthro-furry-avatar-1",
    platforms: ["chillout-vr", "resonite-vr"],
  },
  {
    category: "Avatars",
    subcategory: "Robot & Cyborgs",
    productName: "Robot Cyborg Avatar 1",
    creatorName: "Creator name",
    rating: 5.0,
    price: 45.50,
    slug: "robot-cyborg-avatar-1",
    platforms: ["neos-vr"],
  },
  {
    category: "Fashion",
    subcategory: "Clothes",
    productName: "Fashion Clothes 1",
    creatorName: "Creator name",
    rating: 5.0,
    price: 15.75,
    slug: "fashion-clothes-1",
    platforms: ["vr-chat-quest", "vr-chat-pcvr", "spatial"],
  },
  {
    category: "Fashion",
    subcategory: "Accessories",
    productName: "Fashion Accessories 1",
    creatorName: "Creator name",
    rating: 5.0,
    price: 30.25,
    slug: "fashion-accessories-1",
    platforms: ["cluster", "virtual-cast"],
  },
  // Row 2
  {
    category: "Avatars",
    subcategory: "Human-like",
    productName: "Human-like Avatar 2",
    creatorName: "Creator name",
    rating: 5.0,
    price: 55.99,
    slug: "human-like-avatar-2",
    platforms: ["vr-chat-pcvr", "chillout-vr"],
  },
  {
    category: "Avatars",
    subcategory: "Anthro & Furry",
    productName: "Anthro Furry Avatar 2",
    creatorName: "Creator name",
    rating: 5.0,
    price: 70.50,
    slug: "anthro-furry-avatar-2",
    platforms: ["resonite-vr", "neos-vr"],
  },
  {
    category: "Avatars",
    subcategory: "Robot & Cyborgs",
    productName: "Robot Cyborg Avatar 2",
    creatorName: "Creator name",
    rating: 5.0,
    price: 85.25,
    slug: "robot-cyborg-avatar-2",
    platforms: ["cluster"],
  },
  {
    category: "Fashion",
    subcategory: "Clothes",
    productName: "Fashion Clothes 2",
    creatorName: "Creator name",
    rating: 5.0,
    price: 40.99,
    slug: "fashion-clothes-2",
    platforms: ["vr-chat-quest", "spatial"],
  },
  {
    category: "Fashion",
    subcategory: "Accessories",
    productName: "Fashion Accessories 2",
    creatorName: "Creator name",
    rating: 5.0,
    price: 20.75,
    slug: "fashion-accessories-2",
    platforms: ["virtual-cast", "others"],
  },
  // Row 3
  {
    category: "Avatars",
    subcategory: "Human-like",
    productName: "Human-like Avatar 3",
    creatorName: "Creator name",
    rating: 5.0,
    price: 95.99,
    slug: "human-like-avatar-3",
    platforms: ["vr-chat-quest", "vr-chat-pcvr", "chillout-vr"],
  },
  {
    category: "Avatars",
    subcategory: "Anthro & Furry",
    productName: "Anthro Furry Avatar 3",
    creatorName: "Creator name",
    rating: 5.0,
    price: 60.50,
    slug: "anthro-furry-avatar-3",
    platforms: ["resonite-vr"],
  },
  {
    category: "Avatars",
    subcategory: "Robot & Cyborgs",
    productName: "Robot Cyborg Avatar 3",
    creatorName: "Creator name",
    rating: 5.0,
    price: 75.25,
    slug: "robot-cyborg-avatar-3",
    platforms: ["neos-vr", "cluster"],
  },
  {
    category: "Fashion",
    subcategory: "Clothes",
    productName: "Fashion Clothes 3",
    creatorName: "Creator name",
    rating: 5.0,
    price: 50.99,
    slug: "fashion-clothes-3",
    platforms: ["spatial", "virtual-cast"],
  },
  {
    category: "Fashion",
    subcategory: "Accessories",
    productName: "Fashion Accessories 3",
    creatorName: "Creator name",
    rating: 5.0,
    price: 35.75,
    slug: "fashion-accessories-3",
    platforms: ["others"],
  },
];