
export const products = [
    // Row 1
    {
      category: "Avatars",
      subcategory: "Human-like",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "human-like-avatar-1",
    },
    {
      category: "Avatars",
      subcategory: "Anthro & Furry",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "anthro-furry-avatar-1",
    },
    {
      category: "Avatars",
      subcategory: "Robot & Cyborgs",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "robot-cyborg-avatar-1",
    },
    {
      category: "Fashion",
      subcategory: "Clothes",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "fashion-clothes-1",
    },
    {
      category: "Fashion",
      subcategory: "Accessories",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "fashion-accessories-1",
    },
    // Row 2
    {
      category: "Avatars",
      subcategory: "Human-like",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "human-like-avatar-2",
    },
    {
      category: "Avatars",
      subcategory: "Anthro & Furry",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "anthro-furry-avatar-2",
    },
    {
      category: "Avatars",
      subcategory: "Robot & Cyborgs",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "robot-cyborg-avatar-2",
    },
    {
      category: "Fashion",
      subcategory: "Clothes",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "fashion-clothes-2",
    },
    {
      category: "Fashion",
      subcategory: "Accessories",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "fashion-accessories-2",
    },
    // Row 3
    {
      category: "Avatars",
      subcategory: "Human-like",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "human-like-avatar-3",
    },
    {
      category: "Avatars",
      subcategory: "Anthro & Furry",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "anthro-furry-avatar-3",
    },
    {
      category: "Avatars",
      subcategory: "Robot & Cyborgs",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "robot-cyborg-avatar-3",
    },
    {
      category: "Fashion",
      subcategory: "Clothes",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "fashion-clothes-3",
    },
    {
      category: "Fashion",
      subcategory: "Accessories",
      productName: "Product name",
      creatorName: "Creator name",
      rating: 5.0,
      price: 10.5,
      slug: "fashion-accessories-3",
    },
  ];